#! /bin/bash
for i in {1..17}
do
	echo $i "===============";
	java -cp lib/antlr.jar:classes Micro test/input/"test"$i".micro";
	more test/output/test"$i".parser;
done
#echo "Input: ";
#more test/input/"$1".micro;
