#! /bin/bash
if [$1 != ""]
then
	for i in {1..17}
	do
		echo $i "===============";
		java -cp lib/antlr.jar:classes Micro test/input/"test"$i".micro";
		more test/output/test"$i".parser;
	done
else
	java -cp lib/antlr.jar:classes Micro test/input/$1".micro"
	more test/output/"$1".parser
fi
#echo "Input: ";
#more test/input/"$1".micro;
